version: '3'

networks:
  dockernet:
    external: true

volumes:
  grafana-storage: null
  elasticsearch-storage:
    driver: local
  jenkins-storage:
    driver: local

services:
  elasticsearch:
    image: elasticsearch:7.16.1
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - elasticsearch-storage:/usr/share/elasticsearch/data
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - node.name=node1

  elastichq:
    image: elastichq/elasticsearch-hq:latest
    container_name: elastichq
    ports:
      - "5050:5000"
    depends_on:
      - elasticsearch
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:9200

  grafana:
    container_name: grafana
    image: grafana/grafana:8.2.5
    depends_on:
      - elasticsearch
    user: "1000"
    ports:
      - "3000:3000"
    volumes:
      - grafana-storage:/var/lib/grafana
      - ./ops/grafana/provisioning/datasources:/etc/grafana/provisioning/datasources
      - ./ops/grafana/provisioning/dashboards:/etc/grafana/provisioning/dashboards
      - /etc/localtime:/etc/localtime:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin

  jenkins:
    container_name: jenkins
    build:
      context: ./ops/container/jenkins
    ports:
      - 8080:8080
      - 50000:50000
    depends_on:
      - elasticsearch
    volumes:
      - jenkins-storage:/var/jenkins_home
    env_file: ./ops/container/jenkins/secrets.env